#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "tldraw"
name = "TLDraw"
description.en = "Tiny little drawing app"
description.fr = "Petite application de dessin"

version = "2.3.0~ynh1"

maintainers = ["Raoul de Limezy"]

[upstream]
license = "MIT"
website = "https://tldraw.com"
demo = "https://tldraw.com"
code = "https://github.com/tldraw/tldraw"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "2500M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.sources.main]
    url = "https://github.com/tldraw/tldraw/archive/refs/tags/v2.3.0.tar.gz"
    sha256 = "7f66ab29a755ad085695730690b6be1337c08a727eff687163990d4ecca696d6"
    # Disabled autoupdate for now because it's flooding with PRs which are failing the test
    # The "multiplayer" patch needs to be fixed to be adapted to newer versions
    autoupdate.strategy = "latest_github_tag"

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
